version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - great_expectations checkpoint run person_checkpoint
  post_build:
    commands:
      - great_expectations -y docs build #--site-name s3_bucket
      - aws s3 cp great_expectations/uncommitted/data_docs/local_site s3://e2e-python-test-results/GX_test_results --recursive

reports:
  GX_reports:
    files:
      - /**/*.json
    base-directory: great_expectations/uncommitted/validations/person_validation_suite
    file-format: json




artifacts:
  files:
    - junit-test-results.xml
    - uncommitted/data_docs/**

reports:
  allure:
    files:
      - allure-report/**

post_build:
  commands:
    - aws s3 sync allure-report/ s3://... # Replace with the appropriate S3 bucket path
    - aws s3 sync GX ... # Replace with the appropriate S3 bucket path
