pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages {
        stage('Provision AWS CodePipeline') {
            steps {
                script {
                    odsComponentStageInfrastructure(context, [
                        branchToEnvironmentMapping: ['feature/terraform-jenkins-agent': 'dev'],
                        environment: 'dev'
                    ])
                }
            }
        }

        stage('Trigger AWS CodePipeline') {
            steps {
                script {
                    def pipelineName = 'tf-test-pipeline'
                    awsCodePipelineTrigger(context, pipelineName)
                }
            }
        }

        stage('Wait for AWS CodePipeline Execution') {
            steps {
                script {
                    def pipelineName = 'tf-test-pipeline'
                    awsCodePipelineWaitForExecution(context, pipelineName)
                }
            }
        }

        stage('Retrieve AWS CodePipeline Status') {
            steps {
                script {
                    def pipelineName = 'tf-test-pipeline'
                    def pipelineStatus = sh(returnStdout: true, script: "aws codepipeline get-pipeline-state --name ${pipelineName} --query 'pipelineVersion' --output text")
                    echo "AWS CodePipeline Status: ${pipelineStatus}"
                }
            }
        }
    }
}