aws_region          = "eu-west-1"
bucket_name         = ""
pipeline_name       = ""
build_project_name  = ""
pipeline_role_name  = "codepipeline-role"
codebuild_role_name = ""
source_object_key   = ""
project_name        = "tf-example-project"
